from django.urls import path

from .views import (
    AppointmentFollowUpSendView,
    AppointmentFollowUpView,
    AppointmentWhatsAppSendView,
    EmailTemplateCreateView,
    EmailTemplateDeleteView,
    EmailTemplateListView,
    EmailTemplatePreviewView,
    EmailTemplateUpdateView,
    MessagingSettingView,
    ServiceFollowUpCreateView,
    ServiceFollowUpDeleteView,
    ServiceFollowUpUpdateView,
    WhatsAppConnectionLogoutView,
    WhatsAppConnectionRestartView,
    WhatsAppConnectionStatusView,
    WhatsAppConnectionView,
    WhatsAppSettingCreateView,
    WhatsAppSettingDeleteView,
    WhatsAppSettingListView,
    WhatsAppSettingTestView,
    WhatsAppSettingUpdateView,
)

app_name = "notifications"

urlpatterns = [
    path(
        "mensagens/envio/",
        MessagingSettingView.as_view(),
        name="messaging_setting",
    ),
    path(
        "emails/modelos/",
        EmailTemplateListView.as_view(),
        name="email_template_list",
    ),
    path(
        "emails/modelos/novo/",
        EmailTemplateCreateView.as_view(),
        name="email_template_create",
    ),
    path(
        "emails/modelos/<int:pk>/editar/",
        EmailTemplateUpdateView.as_view(),
        name="email_template_update",
    ),
    path(
        "emails/modelos/<int:pk>/apagar/",
        EmailTemplateDeleteView.as_view(),
        name="email_template_delete",
    ),
    path(
        "emails/modelos/<int:pk>/pre-visualizar/",
        EmailTemplatePreviewView.as_view(),
        name="email_template_preview",
    ),
    path(
        "emails/seguimentos/novo/",
        ServiceFollowUpCreateView.as_view(),
        name="service_followup_create",
    ),
    path(
        "emails/seguimentos/<int:pk>/editar/",
        ServiceFollowUpUpdateView.as_view(),
        name="service_followup_update",
    ),
    path(
        "emails/seguimentos/<int:pk>/apagar/",
        ServiceFollowUpDeleteView.as_view(),
        name="service_followup_delete",
    ),
    path(
        "mensagens/whatsapp/",
        WhatsAppSettingListView.as_view(),
        name="whatsapp_setting_list",
    ),
    path(
        "mensagens/whatsapp/nova/",
        WhatsAppSettingCreateView.as_view(),
        name="whatsapp_setting_create",
    ),
    path(
        "mensagens/whatsapp/<int:pk>/editar/",
        WhatsAppSettingUpdateView.as_view(),
        name="whatsapp_setting_update",
    ),
    path(
        "mensagens/whatsapp/<int:pk>/apagar/",
        WhatsAppSettingDeleteView.as_view(),
        name="whatsapp_setting_delete",
    ),
    path(
        "mensagens/whatsapp/<int:pk>/testar/",
        WhatsAppSettingTestView.as_view(),
        name="whatsapp_setting_test",
    ),
    path(
        "mensagens/whatsapp/ligacao/",
        WhatsAppConnectionView.as_view(),
        name="whatsapp_connection",
    ),
    path(
        "mensagens/whatsapp/ligacao/estado/",
        WhatsAppConnectionStatusView.as_view(),
        name="whatsapp_connection_status",
    ),
    path(
        "mensagens/whatsapp/ligacao/terminar/",
        WhatsAppConnectionLogoutView.as_view(),
        name="whatsapp_connection_logout",
    ),
    path(
        "mensagens/whatsapp/ligacao/reiniciar/",
        WhatsAppConnectionRestartView.as_view(),
        name="whatsapp_connection_restart",
    ),
    path(
        "marcacoes/<int:pk>/seguimentos/",
        AppointmentFollowUpView.as_view(),
        name="appointment_followups",
    ),
    path(
        "marcacoes/<int:pk>/seguimentos/<int:followup_pk>/enviar/",
        AppointmentFollowUpSendView.as_view(),
        name="appointment_followup_send",
    ),
    path(
        "marcacoes/<int:pk>/whatsapp/<int:setting_pk>/enviar/",
        AppointmentWhatsAppSendView.as_view(),
        name="appointment_whatsapp_send",
    ),
]
