# Generated by Django 5.2.17 on 2026-08-28 13:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0043_treatedcondition_hero_image_en"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spent_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Data"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplies", "Material clínico"),
                            ("equipment", "Equipamento"),
                            ("rent", "Renda e despesas do espaço"),
                            ("training", "Formação"),
                            ("travel", "Deslocações"),
                            ("marketing", "Divulgação"),
                            ("taxes", "Impostos e contribuições"),
                            ("other", "Outra"),
                        ],
                        default="supplies",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="O que foi. Exemplo: caixa de compressas, 100 unidades.",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_registered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-spent_on", "-id"],
                "indexes": [
                    models.Index(
                        fields=["spent_on"], name="finance_exp_spent_o_3c5879_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="O que a pessoa pagou. Pode não ser o preço de tabela.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor cobrado",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("mbway", "MB Way"),
                            ("card", "Multibanco"),
                            ("transfer", "Transferência"),
                            ("other", "Outro"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Como pagou",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data do pagamento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="appointments.appointment",
                        verbose_name="Marcação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_registered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-paid_on", "-id"],
                "indexes": [
                    models.Index(
                        fields=["paid_on"], name="finance_pay_paid_on_f3f1d3_idx"
                    )
                ],
            },
        ),
    ]
