# Generated by Django 5.2.17 on 2026-08-28 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counted_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Uma contagem por dia. Contar duas vezes o mesmo dia é ter duas verdades.",
                        unique=True,
                        verbose_name="Dia contado",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pagamentos em dinheiro registados nesse dia.",
                        max_digits=10,
                        verbose_name="O que o sistema diz",
                    ),
                ),
                (
                    "counted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="O que estava na caixa",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="O que explica a diferença, tanto quanto se saiba.",
                        verbose_name="Razão da diferença",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acerto de caixa",
                "verbose_name_plural": "Acertos de caixa",
                "ordering": ["-counted_on"],
            },
        ),
    ]
