# Generated by Django 5.2.17 on 2026-08-28 15:40

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_cashcount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reinvestment_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="De cada pagamento, quanto vai para a conta de investimento. Zero não separa nada.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Percentagem de reinvestimento",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Definição do financeiro",
                "verbose_name_plural": "Definições do financeiro",
            },
        ),
        migrations.AddField(
            model_name="cashcount",
            name="account",
            field=models.CharField(
                choices=[("available", "Disponível"), ("investment", "Investimento")],
                default="available",
                max_length=20,
                verbose_name="Conta",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reinvestment_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="% para investir",
            ),
        ),
        migrations.AlterField(
            model_name="cashcount",
            name="counted_on",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Uma contagem por dia. Contar duas vezes o mesmo dia é ter duas verdades.",
                verbose_name="Dia contado",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcount",
            constraint=models.UniqueConstraint(
                fields=("counted_on", "account"), name="uma_contagem_por_dia_e_conta"
            ),
        ),
    ]
