# Generated by Django 5.1.4 on 2026-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_access_clinical_data",
            field=models.BooleanField(
                default=False,
                help_text="Permite ver e editar fichas de anamnese e notas de evolução. Reservado a quem presta os cuidados.",
                verbose_name="Acesso a dados clínicos",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_internal_staff",
            field=models.BooleanField(
                default=False,
                help_text="Permite gerir marcações, clientes, serviços e agenda. Não dá acesso a informação clínica.",
                verbose_name="Acesso à área interna",
            ),
        ),
    ]
