# Generated by Django 5.1.4 on 2026-08-13 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_access_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        help_text="Devolvido pelo dispositivo, em base64url.",
                        max_length=500,
                        unique=True,
                        verbose_name="Identificador da credencial",
                    ),
                ),
                ("public_key", models.TextField(verbose_name="Chave pública")),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Contador de assinaturas"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Como reconhecer este aparelho na lista.",
                        max_length=80,
                        verbose_name="Dispositivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última utilização"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo com biometria",
                "verbose_name_plural": "Dispositivos com biometria",
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
    ]
