# Generated by Django 5.1.4 on 2026-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_businesshour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_appointment_date_start_time",
        ),
        migrations.AlterUniqueTogether(
            name="businesshour",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Segunda-feira"),
                    (1, "Terça-feira"),
                    (2, "Quarta-feira"),
                    (3, "Quinta-feira"),
                    (4, "Sexta-feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                unique=True,
            ),
        ),
    ]
