# Generated by Django 5.1.4 on 2026-05-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_expand_reminder_log_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appt_date_start_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appt_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appt_customer_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduleblock",
            name="block_date_start_idx",
        ),
    ]
