# Generated by Django 5.1.4 on 2026-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_scheduleblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleblock",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduleblock",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleblock",
            name="recurring_weekdays",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated weekdays. Example: 0,1,2,3,4",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="date",
            field=models.DateField(
                help_text="Use this date for a single block or as the recurrence start date."
            ),
        ),
    ]
