# Generated by Django 5.1.4 on 2026-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_scheduleblock_is_recurring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reference_code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
