# Generated by Django 5.1.4 on 2026-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_service_categories_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="is_coming_soon",
            field=models.BooleanField(default=False),
        ),
    ]
