# Generated by Django 5.1.4 on 2026-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_appointment_unique_active_appointment_per_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Usada nas páginas em /en/. Se ficar vazia, mostra a descrição em português.",
                verbose_name="Descrição (inglês)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="Usado nas páginas em /en/. Se ficar vazio, mostra o nome em português.",
                max_length=120,
                verbose_name="Nome (inglês)",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Usada nas páginas em /en/. Se ficar vazia, mostra a descrição em português.",
                verbose_name="Descrição (inglês)",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="Usado nas páginas em /en/. Se ficar vazio, mostra o nome em português.",
                max_length=120,
                verbose_name="Nome (inglês)",
            ),
        ),
    ]
