# Generated by Django 5.1.4 on 2026-08-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_podiatry_price_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="show_prices",
            field=models.BooleanField(
                default=False,
                help_text="Quando ligado, o preço de cada serviço desta categoria aparece na página inicial e na lista de serviços.",
                verbose_name="Mostrar preços no site",
            ),
        ),
    ]
