# Generated by Django 5.1.4 on 2026-08-10 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0013_enable_prices_for_podiatry_and_laser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_complaint",
                    models.TextField(
                        blank=True,
                        help_text="Queixa principal e há quanto tempo dura.",
                        verbose_name="Motivo da consulta",
                    ),
                ),
                (
                    "has_diabetes",
                    models.BooleanField(default=False, verbose_name="Diabetes"),
                ),
                (
                    "has_circulatory_issues",
                    models.BooleanField(
                        default=False, verbose_name="Problemas de circulação"
                    ),
                ),
                (
                    "has_cardiovascular_issues",
                    models.BooleanField(
                        default=False, verbose_name="Problemas cardiovasculares"
                    ),
                ),
                (
                    "has_allergies",
                    models.BooleanField(default=False, verbose_name="Alergias"),
                ),
                (
                    "is_smoker",
                    models.BooleanField(default=False, verbose_name="Fumadora"),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Obrigatório quando existem alergias.",
                        verbose_name="Quais alergias",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Doenças relevantes não cobertas pelas opções acima.",
                        verbose_name="Outros antecedentes",
                    ),
                ),
                (
                    "current_medication",
                    models.TextField(blank=True, verbose_name="Medicação habitual"),
                ),
                (
                    "previous_surgeries",
                    models.TextField(
                        blank=True, verbose_name="Cirurgias e tratamentos anteriores"
                    ),
                ),
                (
                    "footwear_notes",
                    models.TextField(
                        blank=True,
                        help_text="Tipo de calçado usado, atividade física, tempo em pé.",
                        verbose_name="Calçado e hábitos",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "consent_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Confirma que a cliente foi informada de que estes dados de saúde são registados e para que servem.",
                        verbose_name="Cliente informada sobre o registo clínico",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_record",
                        to="appointments.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_patient_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Última alteração por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de anamnese",
                "verbose_name_plural": "Fichas de anamnese",
                "ordering": ["customer__full_name"],
            },
        ),
    ]
