# Generated by Django 5.1.4 on 2026-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0016_clinical_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesshour",
            name="second_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora final (tarde)"
            ),
        ),
        migrations.AddField(
            model_name="businesshour",
            name="second_start_time",
            field=models.TimeField(
                blank=True,
                help_text="Deixe vazio se trabalhar em período único.",
                null=True,
                verbose_name="Hora inicial (tarde)",
            ),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="end_time",
            field=models.TimeField(verbose_name="Hora final"),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="start_time",
            field=models.TimeField(verbose_name="Hora inicial"),
        ),
    ]
