# Generated by Django 5.1.4 on 2026-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0018_split_working_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="A idade condiciona a avaliação vascular e neurológica.",
                null=True,
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="diabetic_foot_risk",
            field=models.CharField(
                choices=[
                    ("na", "Não aplicável"),
                    ("low", "Baixo"),
                    ("moderate", "Moderado"),
                    ("high", "Alto"),
                ],
                default="na",
                max_length=10,
                verbose_name="Risco de pé diabético",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="foot_deformities",
            field=models.TextField(
                blank=True,
                help_text="Hallux valgus, dedos em garra, pé plano ou cavo, zonas de pressão.",
                verbose_name="Deformidades e apoio",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="gait_assessment",
            field=models.TextField(blank=True, verbose_name="Marcha"),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_coagulation_issues",
            field=models.BooleanField(
                default=False,
                verbose_name="Alterações da coagulação ou anticoagulantes",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_hypertension",
            field=models.BooleanField(
                default=False, verbose_name="Hipertensão arterial"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_kidney_disease",
            field=models.BooleanField(default=False, verbose_name="Doença renal"),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_neuropathy",
            field=models.BooleanField(
                default=False, verbose_name="Neuropatia periférica"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_rheumatic_disease",
            field=models.BooleanField(
                default=False, verbose_name="Doença reumática (artrite, artrose)"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_skin_condition",
            field=models.BooleanField(
                default=False, verbose_name="Doença dermatológica (psoríase, eczema)"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="has_thyroid_disease",
            field=models.BooleanField(
                default=False, verbose_name="Alterações da tiroide"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="is_pregnant",
            field=models.BooleanField(default=False, verbose_name="Grávida"),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="nail_assessment",
            field=models.TextField(
                blank=True,
                help_text="Onicomicose, onicocriptose, onicogrifose, hematoma subungueal.",
                verbose_name="Unhas",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="neurological_assessment",
            field=models.TextField(
                blank=True,
                help_text="Sensibilidade ao monofilamento, diapasão, reflexos.",
                verbose_name="Avaliação neurológica",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="profession",
            field=models.CharField(
                blank=True,
                help_text="Tempo em pé e tipo de calçado de trabalho são relevantes.",
                max_length=120,
                verbose_name="Profissão",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="skin_assessment",
            field=models.TextField(
                blank=True,
                help_text="Hidratação, hiperqueratose, fissuras, maceração interdigital.",
                verbose_name="Pele",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="treatment_plan",
            field=models.TextField(
                blank=True,
                help_text="Cuidados previstos, periodicidade e indicações dadas.",
                verbose_name="Plano de tratamento",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="vascular_assessment",
            field=models.TextField(
                blank=True,
                help_text="Pulsos pedioso e tibial posterior, temperatura, cor, edema.",
                verbose_name="Avaliação vascular",
            ),
        ),
    ]
