# Generated by Django 5.1.4 on 2026-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0019_podiatry_anamnesis"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="outside_schedule",
            field=models.BooleanField(
                default=False,
                help_text="Marcação colocada fora do horário de funcionamento ou sobre um bloqueio, a partir da área interna.",
                verbose_name="Encaixe fora do horário",
            ),
        ),
    ]
