"""Passa a registar a origem das marcações e o que cada alteração mudou.

O que já existia fica marcado como origem desconhecida. Os campos novos têm
`default` para o Django poder acrescentar a coluna, mas aplicá-lo às linhas
antigas seria dizer que todas as marcações anteriores vieram da área interna —
uma afirmação que ninguém verificou e que uma auditoria não pode fazer.
"""

# Generated by Django 5.1.4 on 2026-08-17 21:49

from django.db import migrations, models


def marcar_anteriores_como_desconhecidas(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    AppointmentLog = apps.get_model("appointments", "AppointmentLog")

    Appointment.objects.update(origin="unknown")
    AppointmentLog.objects.update(source="unknown")


def repor(apps, schema_editor):
    # Sem passo atrás: o valor anterior era a ausência da coluna.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0020_appointment_outside_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="origin",
            field=models.CharField(
                choices=[
                    ("public", "Site"),
                    ("internal", "Área interna"),
                    ("unknown", "Desconhecida"),
                ],
                default="internal",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
        migrations.AddField(
            model_name="appointmentlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Alterações"),
        ),
        migrations.AddField(
            model_name="appointmentlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("public", "Site"),
                    ("internal", "Área interna"),
                    ("system", "Automático"),
                    ("unknown", "Desconhecida"),
                ],
                default="internal",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
        migrations.RunPython(marcar_anteriores_como_desconhecidas, repor),
    ]
