# Generated by Django 5.1.4 on 2026-08-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_appointment_origin_appointmentlog_changes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleblock",
            name="title",
        ),
    ]
