# Generated by Django 5.1.4 on 2026-08-20 08:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0022_drop_schedule_block_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Marcação",
                "verbose_name_plural": "Marcações",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleblock",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Bloqueio de agenda",
                "verbose_name_plural": "Bloqueios de agenda",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Motivo do cancelamento"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelada em"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criada por",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reference_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Código da marcação",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.service",
                verbose_name="Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(verbose_name="Hora de início"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendado"),
                    ("confirmed", "Confirmado"),
                    ("cancelled", "Cancelado"),
                    ("completed", "Concluído"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Nome completo"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_guest",
            field=models.BooleanField(default=False, verbose_name="Sem conta no site"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Conta de utilizador",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("break", "Pausa"),
                    ("vacation", "Férias"),
                    ("day_off", "Folga"),
                    ("other", "Outro"),
                ],
                default="other",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="date",
            field=models.DateField(
                help_text="Num bloqueio único, o dia. Num bloqueio que se repete, o dia em que a repetição começa.",
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Hora de fim"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="is_full_day",
            field=models.BooleanField(default=False, verbose_name="Dia inteiro"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Repete-se"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Repete até"),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="recurring_weekdays",
            field=models.CharField(
                blank=True,
                help_text="Dias separados por vírgula. Exemplo: 0,1,2,3,4",
                max_length=20,
                verbose_name="Dias da semana da repetição",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleblock",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de início"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="appointments.servicecategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=60,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Duração (minutos)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço",
            ),
        ),
    ]
