# Generated by Django 5.1.4 on 2026-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0023_portuguese_field_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesshour",
            options={
                "ordering": ["weekday"],
                "verbose_name": "Horário de funcionamento",
                "verbose_name_plural": "Horários de funcionamento",
            },
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Segunda-feira"),
                    (1, "Terça-feira"),
                    (2, "Quarta-feira"),
                    (3, "Quinta-feira"),
                    (4, "Sexta-feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                unique=True,
                verbose_name="Dia da semana",
            ),
        ),
    ]
