# Generated by Django 5.1.4 on 2026-08-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0024_alter_businesshour_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_minutes",
                    models.PositiveIntegerField(
                        choices=[
                            (15, "15 minutos"),
                            (30, "30 minutos"),
                            (60, "1 hora"),
                        ],
                        default=30,
                        help_text="De quanto em quanto tempo a agenda é dividida. Vale para a agenda interna e para os horários oferecidos no site.",
                        verbose_name="Intervalo da grelha",
                    ),
                ),
                (
                    "booking_min_advance_hours",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Horas que têm de faltar para um horário poder ser marcado no site. Zero aceita marcações até à hora exata.",
                        verbose_name="Antecedência mínima para marcar",
                    ),
                ),
                (
                    "booking_horizon_days",
                    models.PositiveIntegerField(
                        default=21,
                        help_text="Quantos dias à frente o site deixa marcar. Encurtar não afeta as marcações que já existem.",
                        verbose_name="Marcações até",
                    ),
                ),
                (
                    "cancellation_min_advance_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Horas que têm de faltar para a cliente ainda poder cancelar sozinha. Passado o prazo, a marcação só é cancelada pela clínica. Zero deixa cancelar até à hora da marcação.",
                        verbose_name="Prazo para cancelar no site",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduling_setting_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regras de agenda",
                "verbose_name_plural": "Regras de agenda",
            },
        ),
    ]
