# Generated by Django 5.1.4 on 2026-08-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0025_scheduling_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmentlog",
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.AlterModelOptions(
            name="patientrecordlog",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "Alteração de ficha",
                "verbose_name_plural": "Alterações de fichas",
            },
        ),
    ]
