# Generated by Django 5.1.4 on 2026-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0026_alter_appointmentlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.CharField(
                choices=[("pt-pt", "Português"), ("en", "English")],
                default="pt-pt",
                help_text="Língua em que esta cliente recebe emails e mensagens.",
                max_length=10,
                verbose_name="Idioma",
            ),
        ),
    ]
