# Generated by Django 5.1.4 on 2026-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0027_customer_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="show_on_homepage",
            field=models.BooleanField(
                default=True,
                help_text="Desligado, a categoria continua marcável e visível na página de serviços, mas deixa de aparecer na página inicial.",
                verbose_name="Mostrar na página inicial",
            ),
        ),
    ]
