# Generated by Django 5.2.17 on 2026-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0031_avaliacao_do_pe_em_ingles"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="home_address",
            field=models.TextField(
                blank=True,
                help_text="Onde a profissional vai. Obrigatória num atendimento em domicílio.",
                verbose_name="Morada do atendimento",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="home_directions",
            field=models.TextField(
                blank=True,
                help_text="Opcional: andar, campainha, onde estacionar, um ponto de referência — o que poupe uma chamada à porta do prédio.",
                verbose_name="Como chegar",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_home_visit",
            field=models.BooleanField(
                default=False,
                help_text="A profissional desloca-se a casa da cliente.",
                verbose_name="Atendimento em domicílio",
            ),
        ),
    ]
