# Generated by Django 5.2.17 on 2026-08-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0033_home_address_in_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer_speaks_english",
            field=models.BooleanField(
                default=False,
                help_text="As mensagens desta marcação saem em inglês.",
                verbose_name="Cliente fala inglês",
            ),
        ),
    ]
