# Generated by Django 5.2.17 on 2026-08-25 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0034_appointment_speaks_english"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="return_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ao concluir um atendimento deste serviço, é este o prazo proposto para a pessoa voltar. Zero não propõe nada.",
                verbose_name="Retorno sugerido (dias)",
            ),
        ),
        migrations.CreateModel(
            name="ReturnVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="A data que se combinou com a pessoa, ainda sem hora.",
                        verbose_name="Voltar por volta de",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Por marcar"),
                            ("scheduled", "Marcado"),
                            ("dismissed", "Dispensado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="O que fica para lembrar quando se ligar à pessoa.",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Avisada em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_visit",
                        to="appointments.appointment",
                        verbose_name="Marcação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_return_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_visits",
                        to="appointments.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns_generated",
                        to="appointments.appointment",
                        verbose_name="Atendimento de origem",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_visits",
                        to="appointments.service",
                        verbose_name="Serviço previsto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retorno",
                "verbose_name_plural": "Retornos",
                "ordering": ["target_date", "customer__full_name"],
            },
        ),
    ]
