# Generated by Django 5.2.17 on 2026-08-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0035_return_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatedCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A parte final do endereço: /o-que-tratamos/unha-encravada/",
                        max_length=140,
                        unique=True,
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Como a pessoa lhe chama. É o título da página.",
                        max_length=120,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome (inglês)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Duas ou três linhas, logo abaixo do título. Serve também de descrição para o Google quando não houver uma escrita à mão.",
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="Resumo (inglês)"),
                ),
                ("what_it_is", models.TextField(verbose_name="O que é")),
                (
                    "what_it_is_en",
                    models.TextField(blank=True, verbose_name="O que é (inglês)"),
                ),
                ("why_it_happens", models.TextField(verbose_name="Porque acontece")),
                (
                    "why_it_happens_en",
                    models.TextField(
                        blank=True, verbose_name="Porque acontece (inglês)"
                    ),
                ),
                (
                    "warning_signs",
                    models.TextField(
                        help_text="O que faz disto uma coisa a não deixar arrastar.",
                        verbose_name="Sinais de alerta",
                    ),
                ),
                (
                    "warning_signs_en",
                    models.TextField(
                        blank=True, verbose_name="Sinais de alerta (inglês)"
                    ),
                ),
                ("how_we_treat", models.TextField(verbose_name="Como se trata aqui")),
                (
                    "how_we_treat_en",
                    models.TextField(
                        blank=True, verbose_name="Como se trata aqui (inglês)"
                    ),
                ),
                ("home_care", models.TextField(verbose_name="Cuidados em casa")),
                (
                    "home_care_en",
                    models.TextField(
                        blank=True, verbose_name="Cuidados em casa (inglês)"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Até 60 caracteres é o que costuma aparecer inteiro.",
                        max_length=70,
                        verbose_name="Título para o Google",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Entre 120 e 155 caracteres é o que costuma aparecer inteiro.",
                        max_length=200,
                        verbose_name="Descrição para o Google",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Separadas por vírgulas.",
                        max_length=255,
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Enquanto estiver desligado, a página não existe para ninguém — nem no site, nem no sitemap.",
                        verbose_name="Publicado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treated_conditions",
                        to="appointments.service",
                        verbose_name="Serviço a propor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problema tratado",
                "verbose_name_plural": "Problemas tratados",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConditionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Pergunta")),
                (
                    "question_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Pergunta (inglês)"
                    ),
                ),
                ("answer", models.TextField(verbose_name="Resposta")),
                (
                    "answer_en",
                    models.TextField(blank=True, verbose_name="Resposta (inglês)"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="appointments.treatedcondition",
                        verbose_name="Problema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta frequente",
                "verbose_name_plural": "Perguntas frequentes",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
