# Generated by Django 5.2.17 on 2026-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0038_risco_podologico"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatedcondition",
            name="hero_alt",
            field=models.CharField(
                blank=True,
                help_text="O que se vê na fotografia, para quem não a consegue ver. Sem isto, a página usa o nome do problema.",
                max_length=180,
                verbose_name="Descrição da imagem",
            ),
        ),
        migrations.AddField(
            model_name="treatedcondition",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Aparece no topo da página e no card do índice. Larga e não alta — é recortada ao meio, e uma fotografia vertical perde as pontas.",
                upload_to="o-que-tratamos/",
                verbose_name="Imagem de abertura",
            ),
        ),
    ]
