# Generated by Django 5.2.17 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0040_condition_rich_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatedcondition",
            name="hero_alt_en",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="Descrição da imagem (inglês)"
            ),
        ),
        migrations.AddField(
            model_name="treatedcondition",
            name="keywords_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Palavras-chave (inglês)"
            ),
        ),
        migrations.AddField(
            model_name="treatedcondition",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Descrição para o Google (inglês)",
            ),
        ),
        migrations.AddField(
            model_name="treatedcondition",
            name="meta_title_en",
            field=models.CharField(
                blank=True, max_length=70, verbose_name="Título para o Google (inglês)"
            ),
        ),
    ]
