# Generated by Django 5.2.17 on 2026-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0042_seed_conditions_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatedcondition",
            name="hero_image_en",
            field=models.ImageField(
                blank=True,
                help_text="Vazio usa a imagem portuguesa. Só vale a pena se o banner tiver texto escrito.",
                upload_to="o-que-tratamos/",
                verbose_name="Imagem de abertura (inglês)",
            ),
        ),
    ]
