# Generated by Django 5.1.4 on 2026-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_whatsappmessagelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        help_text='Cole aqui o código de incorporação do Instagram (no post, clique em "..." → Copiar código de incorporação). Pode colar o bloco inteiro, inclusive a linha &lt;script&gt; — ela é removida automaticamente ao salvar.'
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publicação do Instagram",
                "verbose_name_plural": "Publicações do Instagram",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
