# Generated by Django 5.1.4 on 2026-08-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0020_appointment_outside_schedule"),
        ("notifications", "0004_instagrampost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrampost",
            name="embed_code",
            field=models.TextField(
                help_text='Cole aqui o código de incorporação do Instagram (no post, clique em "..." → Copiar código de incorporação). Pode colar o bloco inteiro, inclusive a linha &lt;script&gt; — ela é removida automaticamente ao guardar.'
            ),
        ),
        migrations.CreateModel(
            name="ServiceFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_after",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Zero envia no próprio dia do atendimento.",
                        verbose_name="Dias depois do atendimento",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para suspender o envio automático. O envio manual continua disponível.",
                        verbose_name="Ativo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="notifications.emailtemplate",
                        verbose_name="Modelo de email",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="O seguimento é enviado a quem fez este serviço.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="appointments.service",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimento por serviço",
                "verbose_name_plural": "Seguimentos por serviço",
                "ordering": ["service__name", "days_after"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "email_template", "days_after"),
                        name="unique_followup_per_service_template_delay",
                    )
                ],
            },
        ),
    ]
