# Generated by Django 5.1.4 on 2026-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0020_appointment_outside_schedule"),
        ("notifications", "0005_alter_instagrampost_embed_code_servicefollowup"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppEventSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("appointment_requested", "Pedido de marcação recebido"),
                            ("appointment_confirmed", "Marcação confirmada"),
                            ("appointment_cancelled", "Marcação cancelada"),
                        ],
                        max_length=50,
                        verbose_name="Acontecimento",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("customer", "Cliente"),
                            ("professional", "Profissional"),
                            ("custom", "Outros números"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="Destinatário",
                    ),
                ),
                (
                    "custom_recipients",
                    models.CharField(
                        blank=True,
                        help_text="Só para 'Outros números'. Separe por vírgulas, com indicativo: +351912345678, +351913333333.",
                        max_length=255,
                        verbose_name="Números",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "body_template",
                    models.TextField(
                        blank=True,
                        help_text="Texto livre, com as mesmas variáveis dos emails. A Twilio só o aceita nas 24 horas seguintes a uma mensagem do destinatário — fora disso é preciso um modelo aprovado.",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "content_sid",
                    models.CharField(
                        blank=True,
                        help_text="Começa por HX. Necessário para mensagens iniciadas pela clínica, que é o caso de tudo o que sai daqui.",
                        max_length=64,
                        verbose_name="Modelo aprovado (Content SID)",
                    ),
                ),
                (
                    "content_variables",
                    models.TextField(
                        blank=True,
                        help_text='JSON com as posições do modelo aprovado. Exemplo: {"1": "{{ customer_name }}", "2": "{{ appointment_date }}"}',
                        verbose_name="Variáveis do modelo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mensagem de WhatsApp",
                "verbose_name_plural": "Mensagens de WhatsApp",
                "ordering": ["event_type", "audience"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="whatsappmessagelog",
            name="unique_success_whatsapp_per_appointment_event_template",
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="audience",
            field=models.CharField(default="customer", max_length=20),
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="provider",
            field=models.CharField(
                choices=[("cloud_api", "WhatsApp Cloud API"), ("twilio", "Twilio")],
                default="cloud_api",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada"),
                    ("appointment_cancelled", "Marcação cancelada"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappmessagelog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "success")),
                fields=(
                    "appointment",
                    "event_type",
                    "template_name",
                    "audience",
                    "provider",
                ),
                name="unique_success_whatsapp_per_appointment_event_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappeventsetting",
            constraint=models.UniqueConstraint(
                fields=("event_type", "audience"),
                name="unique_whatsapp_setting_per_event_audience",
            ),
        ),
    ]
