# Generated by Django 5.1.4 on 2026-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_whatsappeventsetting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappeventsetting",
            name="meta_template_body",
            field=models.TextField(
                blank=True,
                help_text="O mesmo texto com as posições numeradas — {{1}}, {{2}} — para colar no Content Template Builder da Twilio. É este que a Meta revê; o campo acima é o que o sistema envia.",
                verbose_name="Texto para aprovação (Meta)",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappeventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada"),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada"),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                max_length=50,
            ),
        ),
    ]
