# Generated by Django 5.1.4 on 2026-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_seed_default_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="delivery_error_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                help_text="Estado final devolvido pela Twilio: delivered, undelivered, failed.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="delivery_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
