# Generated by Django 5.1.4 on 2026-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_whatsappmessagelog_delivery_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappeventsetting",
            name="provider",
            field=models.CharField(
                choices=[
                    ("twilio", "Twilio"),
                    ("baileys", "Baileys (número da clínica)"),
                ],
                default="twilio",
                help_text="Twilio: precisa de modelo aprovado, mas é um serviço contratado. Baileys: texto livre pelo número da clínica, sem custo, mas depende da ligação por QR code estar de pé.",
                max_length=20,
                verbose_name="Enviar por",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("cloud_api", "WhatsApp Cloud API"),
                    ("twilio", "Twilio"),
                    ("baileys", "Baileys"),
                ],
                default="cloud_api",
                max_length=20,
            ),
        ),
    ]
