# Generated by Django 5.1.4 on 2026-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_remove_email_reminders"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaileventsetting",
            options={"ordering": ["event_type", "name"]},
        ),
        migrations.RemoveConstraint(
            model_name="emaileventsetting",
            name="unique_single_email_setting_per_non_reminder_event",
        ),
        migrations.RemoveConstraint(
            model_name="emaileventsetting",
            name="unique_email_reminder_setting_per_lead_time",
        ),
        migrations.AlterField(
            model_name="emaileventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Pedido de marcação criado"),
                    ("appointment_confirmed", "Marcação confirmada"),
                    ("appointment_cancelled", "Marcação cancelada"),
                ],
                help_text="Ação do sistema que poderá enviar email.",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="emaileventsetting",
            constraint=models.UniqueConstraint(
                fields=("event_type",), name="unique_single_email_setting_per_event"
            ),
        ),
    ]
