# Generated by Django 5.1.4 on 2026-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_appointment_origin_appointmentlog_changes_and_more"),
        ("notifications", "0015_alter_emaileventsetting_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicefollowup",
            options={
                "ordering": ["service__name", "trigger", "days_after"],
                "verbose_name": "Mensagem por serviço",
                "verbose_name_plural": "Mensagens por serviço",
            },
        ),
        migrations.RemoveConstraint(
            model_name="emaileventsetting",
            name="unique_single_email_setting_per_event",
        ),
        migrations.RemoveConstraint(
            model_name="servicefollowup",
            name="unique_followup_per_service_template_delay",
        ),
        migrations.AddField(
            model_name="emaileventsetting",
            name="audience",
            field=models.CharField(
                choices=[("customer", "Cliente"), ("professional", "Profissional")],
                default="customer",
                max_length=20,
                verbose_name="Destinatário",
            ),
        ),
        migrations.AddField(
            model_name="servicefollowup",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("completion", "No fim do atendimento"),
                    ("delayed", "Alguns dias depois"),
                    ("manual", "Só quando for enviada à mão"),
                ],
                default="delayed",
                max_length=20,
                verbose_name="Quando enviar",
            ),
        ),
        migrations.AlterField(
            model_name="emaileventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Pedido de marcação criado"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                help_text="Ação do sistema que poderá enviar email.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicefollowup",
            name="days_after",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Só conta para 'Alguns dias depois'. Zero envia no próprio dia do atendimento.",
                verbose_name="Dias depois do atendimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappeventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="emaileventsetting",
            constraint=models.UniqueConstraint(
                fields=("event_type", "audience"),
                name="unique_email_setting_per_event_and_audience",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicefollowup",
            constraint=models.UniqueConstraint(
                fields=("service", "email_template", "trigger", "days_after"),
                name="unique_service_message_per_template_and_moment",
            ),
        ),
    ]
