# Generated by Django 5.1.4 on 2026-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0018_cancellation_reason_in_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaileventsetting",
            options={
                "ordering": ["event_type", "name"],
                "verbose_name": "Regra de email",
                "verbose_name_plural": "Regras de email",
            },
        ),
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "Modelo de email",
                "verbose_name_plural": "Modelos de email",
            },
        ),
        migrations.AlterField(
            model_name="emaileventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Pedido de marcação criado"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                ],
                help_text="Ação do sistema que poderá enviar email.",
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="emaileventsetting",
            name="name",
            field=models.CharField(
                help_text="Nome interno para identificar esta regra no admin.",
                max_length=150,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body_html",
            field=models.TextField(
                blank=True,
                help_text="Versão em HTML do email. Vazio envia só o texto acima.",
                verbose_name="HTML (opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body_text",
            field=models.TextField(verbose_name="Texto"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                help_text="Identificador interno, sem espaços. Exemplo: appointment_cancelled",
                max_length=100,
                unique=True,
                verbose_name="Identificador",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                help_text="Nome legível, para identificar o modelo nas listas.",
                max_length=150,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Assunto"),
        ),
    ]
