# Generated by Django 5.1.4 on 2026-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0020_messaging_channels"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeforeAfterCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="O que este par mostra. Aparece por cima das fotografias.",
                        max_length=140,
                        verbose_name="Legenda do conjunto",
                    ),
                ),
                (
                    "before_image",
                    models.ImageField(
                        upload_to="antes-e-depois/", verbose_name="Fotografia do antes"
                    ),
                ),
                (
                    "before_caption",
                    models.CharField(
                        blank=True,
                        help_text="Aparece do lado esquerdo, por baixo das fotografias.",
                        max_length=160,
                        verbose_name="Legenda do antes",
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        upload_to="antes-e-depois/", verbose_name="Fotografia do depois"
                    ),
                ),
                (
                    "after_caption",
                    models.CharField(
                        blank=True,
                        help_text="Aparece do lado direito, por baixo das fotografias.",
                        max_length=160,
                        verbose_name="Legenda do depois",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Menor primeiro. Em caso de empate, o mais recente à frente.",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Visível no site"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caso antes e depois",
                "verbose_name_plural": "Casos antes e depois",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
