# Generated by Django 5.1.4 on 2026-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0021_beforeaftercase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beforeaftercase",
            name="after_caption",
        ),
        migrations.RemoveField(
            model_name="beforeaftercase",
            name="before_caption",
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Texto que acompanha o par. Aparece por baixo das fotografias.",
                verbose_name="Legenda da foto",
            ),
        ),
        migrations.AlterField(
            model_name="beforeaftercase",
            name="title",
            field=models.CharField(
                help_text="O que este par mostra. Aparece por cima das fotografias.",
                max_length=140,
                verbose_name="Título da foto",
            ),
        ),
    ]
