# Generated by Django 5.1.4 on 2026-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0022_remove_beforeaftercase_after_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="body_html_en",
            field=models.TextField(blank=True, verbose_name="HTML (inglês)"),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="body_text_en",
            field=models.TextField(blank=True, verbose_name="Texto (inglês)"),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="subject_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Assunto (inglês)"
            ),
        ),
        migrations.AddField(
            model_name="whatsappeventsetting",
            name="body_template_en",
            field=models.TextField(
                blank=True,
                help_text="Deixe vazio para enviar a mensagem em português também a quem marcou na versão inglesa do site.",
                verbose_name="Mensagem (inglês)",
            ),
        ),
        migrations.AddField(
            model_name="whatsappeventsetting",
            name="content_sid_en",
            field=models.CharField(
                blank=True,
                help_text="O modelo equivalente, aprovado em inglês. Vazio envia o modelo português também a quem marcou na versão inglesa.",
                max_length=64,
                verbose_name="Modelo aprovado em inglês (Content SID)",
            ),
        ),
    ]
