# Generated by Django 5.1.4 on 2026-08-23 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0024_seed_english_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="beforeaftercase",
            name="after_focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Ponto do depois (horizontal)",
            ),
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="after_focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Ponto do depois (vertical)",
            ),
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="after_zoom",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Aproximação do depois",
            ),
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="before_focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Ponto do antes (horizontal)",
            ),
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="before_focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Ponto do antes (vertical)",
            ),
        ),
        migrations.AddField(
            model_name="beforeaftercase",
            name="before_zoom",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="100 é a fotografia inteira; 200 é o dobro do tamanho.",
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Aproximação do antes",
            ),
        ),
    ]
