# Generated by Django 5.2.17 on 2026-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0025_beforeaftercase_after_focus_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beforeaftercase",
            name="reveal_orientation",
            field=models.CharField(
                choices=[
                    (
                        "vertical",
                        "Vertical — antes à esquerda, arrasta-se para os lados",
                    ),
                    ("horizontal", "Horizontal — antes em cima, arrasta-se para baixo"),
                ],
                default="vertical",
                help_text="Por onde a linha separa as duas fotografias. Escolha a direção que atravessa o que mudou.",
                max_length=10,
                verbose_name="Barra de comparação",
            ),
        ),
    ]
