# Generated by Django 5.2.17 on 2026-08-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0027_home_visit_in_the_confirmations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaileventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Pedido de marcação criado"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("return_due", "Está na altura de voltar"),
                ],
                help_text="Ação do sistema que poderá enviar email.",
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappeventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("return_due", "Está na altura de voltar"),
                ],
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("return_due", "Está na altura de voltar"),
                ],
                max_length=50,
            ),
        ),
    ]
