# Generated by Django 5.2.17 on 2026-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0029_seed_return_due_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagingsetting",
            name="reminder_hours_before",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Quantas horas antes da marcação sai o lembrete à cliente. Zero não envia lembrete nenhum.",
                verbose_name="Lembrete: horas de antecedência",
            ),
        ),
        migrations.AlterField(
            model_name="emaileventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Pedido de marcação criado"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("appointment_reminder", "Lembrete da marcação"),
                    ("return_due", "Está na altura de voltar"),
                ],
                help_text="Ação do sistema que poderá enviar email.",
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappeventsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("appointment_reminder", "Lembrete da marcação"),
                    ("return_due", "Está na altura de voltar"),
                ],
                max_length=50,
                verbose_name="Acontecimento",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment_requested", "Pedido de marcação recebido"),
                    ("appointment_confirmed", "Marcação confirmada (pedida no site)"),
                    (
                        "appointment_confirmed_internal",
                        "Marcação confirmada (criada na área interna)",
                    ),
                    ("appointment_cancelled", "Marcação cancelada"),
                    ("appointment_completed", "Atendimento concluído"),
                    ("appointment_reminder", "Lembrete da marcação"),
                    ("return_due", "Está na altura de voltar"),
                ],
                max_length=50,
            ),
        ),
    ]
